PERIPHERALS = pwm pit spi adc
DRIVERS = panic usb_serial pacer nrf24 button ledtape
SRC = racer.c bumper_handling.c led_handling.c low_batt_handling.c nrf_handling.c pwm_handling.c sleep_handling.c 

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = racer

include ../../boards/board.mk
