PERIPHERALS = pit adc sam4s
DRIVERS = led pacer adxl345 usb_serial ring nrf24 ledtape piezo button
SRC = hat.c accelBuff.c nrfHandling.c sounds.c lowBatHandling.c ledTapeControl.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
